version: "3"

services:

  uniswap-v3-ms:
    command: python3 app/__main__.py
    restart: always
    ports:
      - '8000:8000'
    build:
      context: ./fastapi/uniswap-v3-ms
      dockerfile: Dockerfile
    environment:
      ETHEREUM_WSS_PROVIDER:
      POLYGON_WSS_PROVIDER:

      BOOTSTRAP_SERVERS: kafka:9092
      PYTHONPATH: ${PYTHONPATH}:/code/app
    depends_on:
      - kafka
    networks:
      - bs-thesis

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - '2182:2182'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - bs-thesis

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - bs-thesis

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: bs.thesis:1:1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_RESTART_ATTEMPTS: 10
      KAFKA_RESTART_DELAY: 5
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
    healthcheck:
      test: nc -z 0.0.0.0 9092 || exit
      interval: 10s
      timeout: 5s
      retries: 15
    depends_on:
      - zookeeper
    networks:
      - bs-thesis

networks:
  bs-thesis: