---
version: '3'

x-common:
  &common
  build:
    context: ./airflow
    dockerfile: Dockerfile
  user: "${AIRFLOW_UID}:0"
  env_file:
    - ./airflow/.env
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/joints:/opt/airflow/joints
  environment:
    PYTHONPATH: "joints:${PYTHONPATH}"

x-depends-on:
  &depends-on
  depends_on:
    postgres:
      condition: service_healthy
    airflow-init:
      condition: service_completed_successfully

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - bs_network

  scheduler:
    <<: *common
    <<: *depends-on
    container_name: airflow-scheduler
    command: scheduler
    restart: on-failure
    ports:
      - "8793:8793"
    networks:
      - bs_network

  webserver:
    <<: *common
    <<: *depends-on
    container_name: airflow-webserver
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://0.0.0.0:8080/health" ]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      - bs_network

  airflow-init:
    <<: *common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    networks:
      - bs_network

networks:
  bs_network: