version: "3"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - '2182:2182'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - real-time-tx-processing

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: real.time.tx.processing:1:1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_RESTART_ATTEMPTS: 10
      KAFKA_RESTART_DELAY: 5
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
    healthcheck:
      test: nc -z 0.0.0.0 9092 || exit
      interval: 10s
      timeout: 5s
      retries: 15
    depends_on:
      - zookeeper
    networks:
      - real-time-tx-processing

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - real-time-tx-processing

  clickhouse:
    image: clickhouse/clickhouse-server:head-alpine
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_HOST: 0.0.0.0
      CLICKHOUSE_DB: clickhouse
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    volumes:
      - ./_modules/clickhouse/docker-entrypoint-initdb.sql:/docker-entrypoint-initdb.d/docker-entrypoint-initdb.sql
    ports:
      - '8123:8123'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8123/ping || exit 1
    restart: always
    depends_on:
      - kafka
    networks:
      - real-time-tx-processing

  postgres:
    image: postgres
    restart: always
    depends_on:
      - clickhouse
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - ./_modules/postgres:/var/lib/postgresql/data
    networks:
      - real-time-tx-processing

  redis:
    image: redis
    restart: always
    depends_on:
      - clickhouse
    networks:
      - real-time-tx-processing

  superset:
    build:
      context: ./_modules/superset/app
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      MAPBOX_API_KEY:
    ports:
      - "8088:8088"
    volumes:
      - ./_modules/superset/app/superset_config.py:/etc/superset/superset_config.py
    networks:
      - real-time-tx-processing

  uniswap-v3-ms:
    command: python3 app/__main__.py
    restart: always
    ports:
      - '8000:8000'
    build:
      context: ./fastapi/uniswap-v3-ms
      dockerfile: Dockerfile
    environment:
      ETHEREUM_WSS_PROVIDER:
      POLYGON_WSS_PROVIDER:

      BOOTSTRAP_SERVERS: kafka:9092
      PYTHONPATH: ${PYTHONPATH}:/code/app
    depends_on:
      - kafka
      - clickhouse
    networks:
      - real-time-tx-processing

networks:
  real-time-tx-processing: