version: "3.2"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    ports:
      - '2182:2182'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - real-time-tx-processing

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: real.time.tx.processing:1:1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_RESTART_ATTEMPTS: 10
      KAFKA_RESTART_DELAY: 5
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
    healthcheck:
      test: nc -z 0.0.0.0 9092 || exit
      interval: 10s
      timeout: 5s
      retries: 15
    depends_on:
      - zookeeper
    networks:
      - real-time-tx-processing

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - real-time-tx-processing

  clickhouse:
    image: clickhouse/clickhouse-server:23.1-alpine
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_HOST: 0.0.0.0
      CLICKHOUSE_DB: clickhouse
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    volumes:
      - ./_modules/clickhouse/docker-entrypoint-initdb.sql:/docker-entrypoint-initdb.d/docker-entrypoint-initdb.sql
    ports:
      - '8123:8123'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8123/ping || exit 1
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - real-time-tx-processing

  postgres:
    image: postgres:15.0-alpine
    restart: always
    depends_on:
      - clickhouse
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - ./_modules/postgres/docker-entrypoint-initdb.sql:/docker-entrypoint-initdb.d/docker-entrypoint-initdb.sql
    networks:
      - real-time-tx-processing

  redis:
    image: redis:7.0-alpine
    restart: always
    depends_on:
      - clickhouse
    networks:
      - real-time-tx-processing

  superset:
    build:
      context: ./_modules/superset
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8088:8088"
    volumes:
      - ./_modules/superset/app/superset_config.py:/etc/superset/superset_config.py
    networks:
      - real-time-tx-processing

  uniswap-v3-ms:
    command: python3 app/__main__.py
    restart: always
    build:
      context: ./fastapi/uniswap-v3-ms
      dockerfile: Dockerfile
    environment:
      ETHEREUM_WSS_PROVIDER:
      POLYGON_WSS_PROVIDER:
      ARBITRUM_WSS_PROVIDER:

      BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_BROKER_URL: kafka
      KAFKA_BROKER_PORT: 9092

      PYTHONPATH: ${PYTHONPATH}:/code/app
    depends_on:
      - kafka-ui
      - clickhouse
    networks:
      - real-time-tx-processing

  quickswap-v3-ms:
    command: python3 app/__main__.py
    restart: always
    build:
      context: ./fastapi/quickswap-v3-ms
      dockerfile: Dockerfile
    environment:
      ETHEREUM_WSS_PROVIDER:
      POLYGON_WSS_PROVIDER:
      ARBITRUM_WSS_PROVIDER:

      BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_BROKER_URL: kafka
      KAFKA_BROKER_PORT: 9092

      PYTHONPATH: ${PYTHONPATH}:/code/app
    depends_on:
      - kafka-ui
      - clickhouse
    networks:
      - real-time-tx-processing

networks:
  real-time-tx-processing:
